services:
  todolist_database:
    image: postgres
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: POSTGRES_USER
      POSTGRES_DB: POSTGRES_DB
      POSTGRES_PASSWORD: POSTGRES_PASSWORD
    ports:
      - "5432:5432"

  todolist_app:
    image: todolist_app
    entrypoint: ./entrypoint.sh
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - todolist_database
    environment:
      DATABASE_URL: DATABASE_URL
volumes:
  pgdata: